package com.christfast.app;

import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;

public class BibleReadingActivity extends AppCompatActivity {

    private static final String PREFS = "BibleReadingPrefs";
    private static final String KEY_DAY = "current_day";

    private TextView readingPlanText, passageText;
    private SharedPreferences prefs;
    private int currentDay = 1;

    private final String[] readings = {
        "Genesis 1:1-31|Creation",
        "Genesis 2:1-25|The Garden of Eden",
        "Genesis 3:1-24|The Fall",
        "Genesis 4:1-26|Cain and Abel",
        "Genesis 6:1-22|Noah and the Flood",
        "Genesis 7:1-24|The Flood",
        "Genesis 8:1-22|The Waters Recede",
        "Genesis 9:1-29|God's Covenant with Noah",
        "Genesis 11:1-32|The Tower of Babel",
        "Genesis 12:1-20|The Call of Abram",
        "Genesis 15:1-21|God's Covenant with Abram",
        "Genesis 17:1-27|The Sign of the Covenant",
        "Genesis 18:1-33|Abraham Intercedes for Sodom",
        "Genesis 19:1-38|Sodom and Gomorrah",
        "Genesis 21:1-34|The Birth of Isaac",
        "Genesis 22:1-24|Abraham Offers Isaac",
        "Genesis 24:1-67|Isaac and Rebekah",
        "Genesis 25:1-34|Jacob and Esau",
        "Genesis 27:1-46|Jacob Steals the Blessing",
        "Genesis 28:1-22|Jacob's Ladder",
        "Genesis 29:1-35|Jacob Marries Leah and Rachel",
        "Genesis 30:1-43|Jacob's Children",
        "Genesis 32:1-32|Jacob Wrestles with God",
        "Genesis 37:1-36|Joseph Sold by His Brothers",
        "Genesis 39:1-23|Joseph and Potiphar's Wife",
        "Genesis 40:1-23|Joseph Interprets Dreams",
        "Genesis 41:1-57|Joseph Rises to Power",
        "Genesis 45:1-28|Joseph Reveals Himself",
        "Genesis 50:1-26|Joseph Forgives His Brothers",
        "Exodus 1:1-22|Israel Enslaved in Egypt",
        "Exodus 3:1-22|The Burning Bush",
        "Exodus 4:1-31|Moses Returns to Egypt",
        "Exodus 12:1-51|The Passover",
        "Exodus 14:1-31|Crossing the Red Sea",
        "Exodus 16:1-36|Manna from Heaven",
        "Exodus 20:1-26|The Ten Commandments",
        "Exodus 32:1-35|The Golden Calf",
        "Exodus 34:1-35|The New Tablets",
        "Leviticus 16:1-34|The Day of Atonement",
        "Leviticus 19:1-37|Holiness Laws",
        "Numbers 6:1-27|The Nazirite Vow",
        "Numbers 13:1-33|Spies Sent to Canaan",
        "Numbers 14:1-45|Israel's Rebellion",
        "Numbers 20:1-29|Water from the Rock",
        "Numbers 21:1-35|The Bronze Serpent",
        "Deuteronomy 6:1-25|Love the LORD Your God",
        "Deuteronomy 8:1-20|Remember the LORD",
        "Deuteronomy 28:1-68|Blessings and Curses",
        "Deuteronomy 30:1-20|Choose Life",
        "Deuteronomy 34:1-12|The Death of Moses",
        "Joshua 1:1-18|God Commissions Joshua",
        "Joshua 2:1-24|Rahab and the Spies",
        "Joshua 3:1-17|Crossing the Jordan",
        "Joshua 4:1-24|Memorial Stones",
        "Joshua 5:1-15|Circumcision and Passover",
        "Joshua 6:1-27|The Fall of Jericho",
        "Joshua 7:1-26|Achan's Sin",
        "Joshua 10:1-43|The Sun Stands Still",
        "Joshua 24:1-33|Joshua's Farewell",
        "Judges 2:1-23|Israel's Disobedience",
        "Judges 4:1-24|Deborah and Barak",
        "Judges 6:1-40|Gideon's Call",
        "Judges 7:1-25|Gideon's Victory",
        "Judges 11:1-40|Jephthah's Vow",
        "Judges 13:1-25|The Birth of Samson",
        "Judges 16:1-31|Samson and Delilah",
        "Ruth 1:1-22|Ruth's Loyalty",
        "Ruth 2:1-23|Ruth Meets Boaz",
        "Ruth 4:1-22|Boaz Redeems Ruth",
        "1 Samuel 1:1-28|Hannah's Prayer",
        "1 Samuel 3:1-21|Samuel's Calling",
        "1 Samuel 8:1-22|Israel Asks for a King",
        "1 Samuel 9:1-27|Saul Anointed King",
        "1 Samuel 16:1-23|David Anointed",
        "1 Samuel 17:1-58|David and Goliath",
        "1 Samuel 18:1-30|David and Jonathan",
        "1 Samuel 24:1-22|David Spares Saul",
        "2 Samuel 5:1-25|David King Over Israel",
        "2 Samuel 6:1-23|The Ark Brought to Jerusalem",
        "2 Samuel 7:1-29|God's Covenant with David",
        "2 Samuel 11:1-27|David and Bathsheba",
        "2 Samuel 12:1-31|Nathan Rebukes David",
        "2 Samuel 22:1-51|David's Song of Praise",
        "1 Kings 2:1-46|Solomon's Throne Established",
        "1 Kings 3:1-28|Solomon's Wisdom",
        "1 Kings 6:1-38|Building the Temple",
        "1 Kings 8:1-66|The Temple Dedicated",
        "1 Kings 10:1-29|The Queen of Sheba",
        "1 Kings 11:1-43|Solomon's Downfall",
        "1 Kings 12:1-33|The Kingdom Divides",
        "1 Kings 17:1-24|Elijah and the Widow",
        "1 Kings 18:1-46|Elijah on Mount Carmel",
        "1 Kings 19:1-21|Elijah at Horeb",
        "2 Kings 2:1-25|Elijah Taken to Heaven",
        "2 Kings 4:1-44|Elisha's Miracles",
        "2 Kings 5:1-27|Naaman Healed",
        "2 Kings 6:1-23|Chariots of Fire",
        "2 Kings 18:1-37|Hezekiah's Reforms",
        "2 Kings 19:1-37|Hezekiah's Prayer",
        "2 Kings 22:1-20|Josiah's Reforms",
        "2 Kings 25:1-30|The Fall of Jerusalem",
        "1 Chronicles 16:1-43|David's Psalm of Thanks",
        "1 Chronicles 17:1-27|God's Covenant with David",
        "1 Chronicles 21:1-30|David's Census",
        "1 Chronicles 29:1-30|David's Final Words",
        "2 Chronicles 7:1-22|God's Response to Solomon",
        "2 Chronicles 20:1-37|Jehoshaphat's Victory",
        "2 Chronicles 24:1-27|Joash Repairs the Temple",
        "2 Chronicles 36:1-23|The Fall of Jerusalem",
        "Ezra 1:1-11|Cyrus Decrees Return",
        "Ezra 3:1-13|Rebuilding the Altar",
        "Ezra 6:1-22|The Temple Completed",
        "Ezra 8:1-36|Ezra's Return",
        "Nehemiah 1:1-11|Nehemiah's Prayer",
        "Nehemiah 2:1-20|Nehemiah Inspects the Walls",
        "Nehemiah 4:1-23|Opposition to Rebuilding",
        "Nehemiah 8:1-18|Ezra Reads the Law",
        "Esther 2:1-23|Esther Becomes Queen",
        "Esther 3:1-15|Haman's Plot",
        "Esther 4:1-17|Esther's Fast",
        "Esther 6:1-14|Mordecai Honored",
        "Esther 8:1-17|The Jews Delivered",
        "Job 1:1-22|Job's Trials Begin",
        "Job 2:1-13|Job's Suffering",
        "Job 19:1-29|Job's Redeemer Lives",
        "Job 38:1-41|God Speaks to Job",
        "Job 42:1-17|Job's Restoration",
        "Psalm 1:1-6|The Righteous and the Wicked",
        "Psalm 8:1-9|God's Glory and Man",
        "Psalm 19:1-14|The Heavens Declare",
        "Psalm 23:1-6|The LORD Is My Shepherd",
        "Psalm 27:1-14|The LORD Is My Light",
        "Psalm 32:1-11|Forgiveness",
        "Psalm 34:1-22|Praise for Deliverance",
        "Psalm 37:1-40|Trust in the LORD",
        "Psalm 42:1-11|As the Deer Pants",
        "Psalm 46:1-11|God Is Our Refuge",
        "Psalm 51:1-19|A Prayer of Repentance",
        "Psalm 62:1-12|Rest in God Alone",
        "Psalm 63:1-11|Thirsting for God",
        "Psalm 84:1-12|Better Is One Day",
        "Psalm 90:1-17|Teach Us to Number Our Days",
        "Psalm 91:1-16|The Shelter of the Most High",
        "Psalm 100:1-5|Enter His Gates with Thanksgiving",
        "Psalm 103:1-22|Praise the LORD, O My Soul",
        "Psalm 119:1-176|The Word of God",
        "Psalm 121:1-8|I Lift Up My Eyes",
        "Psalm 139:1-24|You Have Searched Me",
        "Psalm 145:1-21|Great Is the LORD",
        "Proverbs 1:1-33|Wisdom's Call",
        "Proverbs 3:1-35|Trust in the LORD",
        "Proverbs 4:1-27|Wisdom Is Supreme",
        "Proverbs 8:1-36|Wisdom's Plea",
        "Proverbs 11:1-31|Honesty and Humility",
        "Proverbs 15:1-33|The Tongue and the Heart",
        "Proverbs 16:1-33|Commit Your Works",
        "Proverbs 22:1-29|A Good Name",
        "Proverbs 31:1-31|The Virtuous Woman",
        "Ecclesiastes 1:1-18|Everything Is Vanity",
        "Ecclesiastes 3:1-22|A Time for Everything",
        "Ecclesiastes 12:1-14|Remember Your Creator",
        "Isaiah 1:1-31|The Wickedness of Judah",
        "Isaiah 6:1-13|Isaiah's Vision",
        "Isaiah 7:1-25|Immanuel Prophecy",
        "Isaiah 9:1-21|A Child Is Born",
        "Isaiah 11:1-16|The Branch of Jesse",
        "Isaiah 40:1-31|Comfort, Comfort My People",
        "Isaiah 43:1-28|Fear Not, I Have Redeemed You",
        "Isaiah 53:1-12|The Suffering Servant",
        "Isaiah 55:1-13|Come to the Waters",
        "Isaiah 58:1-14|True Fasting",
        "Isaiah 61:1-11|The Year of the LORD's Favor",
        "Jeremiah 1:1-19|The Call of Jeremiah",
        "Jeremiah 7:1-34|False Religion",
        "Jeremiah 18:1-23|The Potter and the Clay",
        "Jeremiah 29:1-32|Plans to Prosper You",
        "Jeremiah 31:1-40|A New Covenant",
        "Lamentations 3:1-66|Great Is Thy Faithfulness",
        "Ezekiel 1:1-28|Ezekiel's Vision",
        "Ezekiel 18:1-32|The Soul Who Sins",
        "Ezekiel 34:1-31|The Good Shepherd",
        "Ezekiel 37:1-28|The Valley of Dry Bones",
        "Daniel 1:1-21|Daniel's Faithfulness",
        "Daniel 2:1-49|Nebuchadnezzar's Dream",
        "Daniel 3:1-30|The Fiery Furnace",
        "Daniel 6:1-28|Daniel in the Lions' Den",
        "Daniel 9:1-27|Daniel's Prayer",
        "Hosea 2:1-23|God's Love for Israel",
        "Hosea 11:1-12|God's Compassion",
        "Joel 2:1-32|The Day of the LORD",
        "Amos 5:1-27|Seek the LORD and Live",
        "Amos 9:1-15|Israel's Restoration",
        "Obadiah 1:1-21|Judgment on Edom",
        "Jonah 1:1-17|Jonah Flees",
        "Jonah 3:1-10|Nineveh Repents",
        "Micah 6:1-16|What the LORD Requires",
        "Nahum 1:1-15|The LORD's Anger",
        "Habakkuk 3:1-19|Habakkuk's Prayer",
        "Zephaniah 3:1-20|The Restoration of Israel",
        "Haggai 2:1-23|The LORD's House",
        "Zechariah 9:1-17|The Coming King",
        "Malachi 3:1-18|The Messenger",
        "Malachi 4:1-6|The Day of the LORD",
        "Matthew 1:1-25|The Genealogy of Jesus",
        "Matthew 2:1-23|The Visit of the Magi",
        "Matthew 3:1-17|The Baptism of Jesus",
        "Matthew 4:1-25|The Temptation of Jesus",
        "Matthew 5:1-48|The Beatitudes",
        "Matthew 6:1-34|Teaching on Prayer and Fasting",
        "Matthew 7:1-29|Judging Others",
        "Matthew 8:1-34|Jesus Heals",
        "Matthew 9:1-38|Jesus Calls Matthew",
        "Matthew 10:1-42|The Twelve Apostles",
        "Matthew 11:1-30|Come to Me",
        "Matthew 12:1-50|Lord of the Sabbath",
        "Matthew 13:1-58|The Parables of the Kingdom",
        "Matthew 14:1-36|Jesus Walks on Water",
        "Matthew 15:1-39|Clean and Unclean",
        "Matthew 16:1-28|Peter's Confession",
        "Matthew 17:1-27|The Transfiguration",
        "Matthew 18:1-35|The Unforgiving Servant",
        "Matthew 19:1-30|The Rich Young Man",
        "Matthew 20:1-34|The Workers in the Vineyard",
        "Matthew 21:1-46|The Triumphal Entry",
        "Matthew 22:1-46|The Greatest Commandment",
        "Matthew 23:1-39|Woes to the Pharisees",
        "Matthew 24:1-51|Signs of the End",
        "Matthew 25:1-46|The Ten Virgins",
        "Matthew 26:1-75|The Last Supper",
        "Matthew 27:1-66|The Crucifixion",
        "Matthew 28:1-20|The Resurrection",
        "Mark 1:1-45|The Beginning of the Gospel",
        "Mark 2:1-28|Jesus Heals a Paralytic",
        "Mark 3:1-35|The Twelve Appointed",
        "Mark 4:1-41|The Parable of the Sower",
        "Mark 5:1-43|Jesus Heals Jairus' Daughter",
        "Mark 6:1-56|Jesus Feeds the Five Thousand",
        "Mark 7:1-37|Clean and Unclean",
        "Mark 8:1-38|Peter's Confession",
        "Mark 9:1-50|The Transfiguration",
        "Mark 10:1-52|The Rich Young Man",
        "Mark 11:1-33|The Triumphal Entry",
        "Mark 12:1-44|The Greatest Commandment",
        "Mark 13:1-37|Signs of the End",
        "Mark 14:1-72|The Last Supper",
        "Mark 15:1-47|The Crucifixion",
        "Mark 16:1-20|The Resurrection",
        "Luke 1:1-80|The Birth of John the Baptist",
        "Luke 2:1-52|The Birth of Jesus",
        "Luke 3:1-38|The Baptism of Jesus",
        "Luke 4:1-44|The Temptation of Jesus",
        "Luke 5:1-39|Jesus Calls the First Disciples",
        "Luke 6:1-49|The Beatitudes",
        "Luke 7:1-50|Jesus Forgives a Sinner",
        "Luke 8:1-56|The Parable of the Sower",
        "Luke 9:1-62|Peter's Confession",
        "Luke 10:1-42|The Good Samaritan",
        "Luke 11:1-54|The Lord's Prayer",
        "Luke 12:1-59|The Rich Fool",
        "Luke 13:1-35|The Narrow Door",
        "Luke 14:1-35|The Great Banquet",
        "Luke 15:1-32|The Prodigal Son",
        "Luke 16:1-31|The Rich Man and Lazarus",
        "Luke 17:1-37|The Ten Lepers",
        "Luke 18:1-43|The Pharisee and the Tax Collector",
        "Luke 19:1-48|Zacchaeus",
        "Luke 20:1-47|The Authority of Jesus",
        "Luke 21:1-38|The Widow's Offering",
        "Luke 22:1-71|The Last Supper",
        "Luke 23:1-56|The Crucifixion",
        "Luke 24:1-53|The Resurrection",
        "John 1:1-51|The Word Became Flesh",
        "John 2:1-25|The Wedding at Cana",
        "John 3:1-36|Nicodemus",
        "John 4:1-54|The Woman at the Well",
        "John 5:1-47|The Healing at Bethesda",
        "John 6:1-71|The Bread of Life",
        "John 7:1-53|The Feast of Tabernacles",
        "John 8:1-59|The Light of the World",
        "John 9:1-41|The Man Born Blind",
        "John 10:1-42|The Good Shepherd",
        "John 11:1-57|The Raising of Lazarus",
        "John 12:1-50|The Triumphal Entry",
        "John 13:1-38|The Last Supper",
        "John 14:1-31|The Way, the Truth, and the Life",
        "John 15:1-27|The Vine and the Branches",
        "John 16:1-33|The Work of the Spirit",
        "John 17:1-26|Jesus' High Priestly Prayer",
        "John 18:1-40|The Arrest of Jesus",
        "John 19:1-42|The Crucifixion",
        "John 20:1-31|The Resurrection",
        "John 21:1-25|Jesus Restores Peter",
        "Acts 1:1-26|The Ascension",
        "Acts 2:1-47|The Day of Pentecost",
        "Acts 3:1-26|Peter Heals a Lame Beggar",
        "Acts 4:1-37|Peter and John Arrested",
        "Acts 5:1-42|Ananias and Sapphira",
        "Acts 6:1-15|The Seven Deacons",
        "Acts 7:1-60|Stephen's Martyrdom",
        "Acts 8:1-40|Philip and the Ethiopian",
        "Acts 9:1-43|The Conversion of Saul",
        "Acts 10:1-48|Peter and Cornelius",
        "Acts 11:1-30|The Church at Antioch",
        "Acts 12:1-25|Peter Escapes Prison",
        "Acts 13:1-52|Paul's First Missionary Journey",
        "Acts 14:1-28|Paul and Barnabas in Lystra",
        "Acts 15:1-41|The Jerusalem Council",
        "Acts 16:1-40|Paul and Silas in Prison",
        "Acts 17:1-34|Paul in Athens",
        "Acts 18:1-28|Paul in Corinth",
        "Acts 19:1-41|Paul in Ephesus",
        "Acts 20:1-38|Paul's Farewell",
        "Acts 21:1-40|Paul Arrested",
        "Acts 22:1-30|Paul's Defense",
        "Acts 23:1-35|Paul Before the Council",
        "Acts 24:1-27|Paul Before Felix",
        "Acts 25:1-27|Paul Appeals to Caesar",
        "Acts 26:1-32|Paul Before Agrippa",
        "Acts 27:1-44|The Shipwreck",
        "Acts 28:1-31|Paul in Rome",
        "Romans 1:1-32|The Gospel Power",
        "Romans 2:1-29|God's Righteous Judgment",
        "Romans 3:1-31|Righteousness Through Faith",
        "Romans 4:1-25|Abraham Justified by Faith",
        "Romans 5:1-21|Peace with God",
        "Romans 6:1-23|Dead to Sin",
        "Romans 7:1-25|The Struggle with Sin",
        "Romans 8:1-39|Life in the Spirit",
        "Romans 9:1-33|God's Sovereignty",
        "Romans 10:1-21|Salvation for All",
        "Romans 11:1-36|Israel's Remnant",
        "Romans 12:1-21|Living Sacrifices",
        "Romans 13:1-14|Submission to Authorities",
        "Romans 14:1-23|The Weak and the Strong",
        "Romans 15:1-33|The Example of Christ",
        "Romans 16:1-27|Final Greetings",
        "1 Corinthians 1:1-31|The Wisdom of the Cross",
        "1 Corinthians 2:1-16|God's Wisdom",
        "1 Corinthians 3:1-23|Building on the Foundation",
        "1 Corinthians 5:1-13|Church Discipline",
        "1 Corinthians 6:1-20|Glorify God in Your Body",
        "1 Corinthians 7:1-40|Marriage",
        "1 Corinthians 9:1-27|Paul's Rights",
        "1 Corinthians 10:1-33|Warning Against Idolatry",
        "1 Corinthians 11:1-34|The Lord's Supper",
        "1 Corinthians 12:1-31|Spiritual Gifts",
        "1 Corinthians 13:1-13|The Greatest Is Love",
        "1 Corinthians 14:1-40|Prophecy and Tongues",
        "1 Corinthians 15:1-58|The Resurrection",
        "1 Corinthians 16:1-24|Final Instructions",
        "2 Corinthians 1:1-24|Comfort in Affliction",
        "2 Corinthians 3:1-18|The New Covenant",
        "2 Corinthians 4:1-18|Treasure in Jars of Clay",
        "2 Corinthians 5:1-21|The Ministry of Reconciliation",
        "2 Corinthians 6:1-18|Paul's Hardships",
        "2 Corinthians 8:1-24|Generosity",
        "2 Corinthians 9:1-15|Cheerful Giving",
        "2 Corinthians 10:1-18|Paul's Authority",
        "2 Corinthians 11:1-33|Paul's Sufferings",
        "2 Corinthians 12:1-21|Paul's Thorn",
        "2 Corinthians 13:1-14|Final Warnings",
        "Galatians 1:1-24|No Other Gospel",
        "Galatians 2:1-21|Justified by Faith",
        "Galatians 3:1-29|Faith and the Law",
        "Galatians 4:1-31|Sons and Heirs",
        "Galatians 5:1-26|Freedom in Christ",
        "Galatians 6:1-18|Bear One Another's Burdens",
        "Ephesians 1:1-23|Spiritual Blessings",
        "Ephesians 2:1-22|Saved by Grace",
        "Ephesians 3:1-21|The Mystery of Christ",
        "Ephesians 4:1-32|Unity in the Body",
        "Ephesians 5:1-33|Walk in Love",
        "Ephesians 6:1-24|The Armor of God",
        "Philippians 1:1-30|Partnership in the Gospel",
        "Philippians 2:1-30|The Humility of Christ",
        "Philippians 3:1-21|Rejoice in the Lord",
        "Philippians 4:1-23|Peace of God",
        "Colossians 1:1-29|The Supremacy of Christ",
        "Colossians 2:1-23|Fullness in Christ",
        "Colossians 3:1-25|Put On the New Self",
        "Colossians 4:1-18|Final Greetings",
        "1 Thessalonians 1:1-10|Thanksgiving",
        "1 Thessalonians 2:1-20|Paul's Ministry",
        "1 Thessalonians 3:1-13|Encouragement",
        "1 Thessalonians 4:1-18|The Coming of the Lord",
        "1 Thessalonians 5:1-28|The Day of the Lord",
        "2 Thessalonians 1:1-12|God's Judgment",
        "2 Thessalonians 2:1-17|The Man of Lawlessness",
        "2 Thessalonians 3:1-18|Request for Prayer",
        "1 Timothy 1:1-20|Warnings Against False Teachers",
        "1 Timothy 2:1-15|Instructions for Worship",
        "1 Timothy 3:1-16|Qualifications for Overseers",
        "1 Timothy 4:1-16|Training in Godliness",
        "1 Timothy 5:1-25|Instructions for the Church",
        "1 Timothy 6:1-21|Godliness with Contentment",
        "2 Timothy 1:1-18|Guard the Gospel",
        "2 Timothy 2:1-26|A Good Soldier",
        "2 Timothy 3:1-17|The Last Days",
        "2 Timothy 4:1-22|Preach the Word",
        "Titus 1:1-16|Appointing Elders",
        "Titus 2:1-15|Sound Doctrine",
        "Titus 3:1-15|Good Works",
        "Philemon 1:1-25|Paul's Plea for Onesimus",
        "Hebrews 1:1-14|God Has Spoken",
        "Hebrews 2:1-18|The Son's Humanity",
        "Hebrews 3:1-19|Christ Is Faithful",
        "Hebrews 4:1-16|The Rest of God",
        "Hebrews 5:1-14|The High Priest",
        "Hebrews 6:1-20|The Anchor of Hope",
        "Hebrews 7:1-28|Melchizedek",
        "Hebrews 8:1-13|The New Covenant",
        "Hebrews 9:1-28|The Blood of Christ",
        "Hebrews 10:1-39|A Better Sacrifice",
        "Hebrews 11:1-40|Faith",
        "Hebrews 12:1-29|Fix Your Eyes on Jesus",
        "Hebrews 13:1-25|Final Exhortations",
        "James 1:1-27|Trials and Temptations",
        "James 2:1-26|Faith and Works",
        "James 3:1-18|The Tongue",
        "James 4:1-17|Submit to God",
        "James 5:1-20|Patience in Suffering",
        "1 Peter 1:1-25|A Living Hope",
        "1 Peter 2:1-25|The Living Stone",
        "1 Peter 3:1-22|Suffering for Righteousness",
        "1 Peter 4:1-19|Stewards of Grace",
        "1 Peter 5:1-14|Shepherd the Flock",
        "2 Peter 1:1-21|Partakers of the Divine Nature",
        "2 Peter 2:1-22|False Teachers",
        "2 Peter 3:1-18|The Day of the Lord",
        "1 John 1:1-10|Walking in the Light",
        "1 John 2:1-29|Love One Another",
        "1 John 3:1-24|Children of God",
        "1 John 4:1-21|God Is Love",
        "1 John 5:1-21|Faith in the Son",
        "2 John 1:1-13|Truth and Love",
        "3 John 1:1-14|Gaius and Diotrephes",
        "Jude 1:1-25|Contend for the Faith",
        "Revelation 1:1-20|The Vision of Christ",
        "Revelation 2:1-29|The Seven Churches",
        "Revelation 3:1-22|The Seven Churches",
        "Revelation 4:1-11|The Throne of God",
        "Revelation 5:1-14|The Lion and the Lamb",
        "Revelation 6:1-17|The Seals",
        "Revelation 7:1-17|The Great Multitude",
        "Revelation 8:1-13|The Trumpets",
        "Revelation 9:1-21|The Trumpets",
        "Revelation 10:1-11|The Angel and the Scroll",
        "Revelation 11:1-19|The Two Witnesses",
        "Revelation 12:1-17|The Woman and the Dragon",
        "Revelation 13:1-18|The Beast",
        "Revelation 14:1-20|The Lamb and the 144,000",
        "Revelation 15:1-8|The Bowls of Wrath",
        "Revelation 16:1-21|The Bowls of Wrath",
        "Revelation 17:1-18|The Woman on the Beast",
        "Revelation 18:1-24|The Fall of Babylon",
        "Revelation 19:1-21|The Marriage of the Lamb",
        "Revelation 20:1-15|The Thousand Years",
        "Revelation 21:1-27|A New Heaven and a New Earth",
        "Revelation 22:1-21|The River of Life"
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_bible_reading);
        prefs = getSharedPreferences(PREFS, MODE_PRIVATE);
        currentDay = prefs.getInt(KEY_DAY, 1);
        readingPlanText = findViewById(R.id.readingPlanText);
        passageText = findViewById(R.id.passageText);
        Button markCompleteButton = findViewById(R.id.markCompleteButton);
        Button prevButton = findViewById(R.id.prevDayButton);
        loadDailyReading();
        markCompleteButton.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) {
                if (currentDay < readings.length) {
                    currentDay++;
                    prefs.edit().putInt(KEY_DAY, currentDay).commit();
                    loadDailyReading();
                }
            }
        });
        prevButton.setOnClickListener(new View.OnClickListener() {
            @Override public void onClick(View v) {
                if (currentDay > 1) {
                    currentDay--;
                    prefs.edit().putInt(KEY_DAY, currentDay).commit();
                    loadDailyReading();
                }
            }
        });
    }

    private void loadDailyReading() {
        readingPlanText.setText("Day " + currentDay + " of " + readings.length);
        String[] parts = readings[(currentDay - 1) % readings.length].split("\\|");
        String ref = parts[0];
        String theme = parts.length > 1 ? parts[1] : "";
        String display = ref + "\n\n" + theme;
        BibleLinkUtils.linkify(this, passageText, display);
    }
}
